services:
  # Для просмотра таблиц через веб-интерфейс (для разработки)
  adminer:
    image: adminer
    restart: always
    ports:
      - "7080:8080"

  # Сервис PostgreSQL
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_HOST=$DB_HOST
    ports:
      - "8432:5432" # Проброс порта для подключения извне (например, через DBeaver)
    volumes:
      - pgdata:/var/lib/postgresql/data # Сохранение данных БД

  # Сервис для сохранения сессии пользователей
  redis:
    image: redis:7-alpine
    ports:
      - "8379:8379"
    command: redis-server --port 8379 --appendonly yes  # <-- заставляем Redis слушать 8379
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "8379", "ping"]  # <-- healthcheck тоже на 8379
      interval: 10s
      timeout: 5s
      retries: 5


  # Сервис приложения FastAPI
  app:
#    image: python:3.14.3-slim
    build: .
    restart: always
    ports:
      - "8800:8800"
    depends_on:
      - postgres
      - redis
    environment:
      # при локальном запуске используем @localhost (see ./app/database/connection.py)
      - TZ=Europe/Moscow
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}${DB_HOST}:5432/${DB_NAME}
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - SESSION_PREFIX=$SESSION_PREFIX
      - SESSION_TTL=$SESSION_TTL
      - ZUP_BASE_URL=ZUP_BASE_URL
      - ZUP_LOGIN=$ZUP_LOGIN
      - ZUP_PASSWORD=$ZUP_PASSWORD
    volumes:
      - .:/app # Для "горячей перезагрузки" при разработке (чтобы изменения кода применялись сразу)
      - ./logs:/logs

volumes:
  pgdata:
  redis_data: